In [2]:
import seaborn as sns
df = sns.load_dataset('titanic')
import numpy as np
import pandas as pd

In [3]:
Df = df.to_csv('titanic.csv', index=False)

In [4]:
df.sample(4)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
643         1       3    male   NaN      0      0  56.4958        S  Third   
271         1       3    male  25.0      0      0   0.0000        S  Third   
678         0       3  female  43.0      1      6  46.9000        S  Third   
131         0       3    male  20.0      0      0   7.0500        S  Third   

       who  adult_male deck  embark_town alive  alone  
643    man        True  NaN  Southampton   yes   True  
271    man        True  NaN  Southampton   yes   True  
678  woman       False  NaN  Southampton    no  False  
131    man        True  NaN  Southampton    no   True

In [5]:
df = df[['sex', 'embarked', 'alone', 'pclass', 'survived']]
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [7]:
df['sex'] = np.where(df['sex'] == 'male', 1, 0)
df.head()

sex embarked  alone  pclass  survived
0    0        S  False       3         0
1    0        C  False       1         1
2    0        S   True       3         1
3    0        S  False       1         1
4    0        S   True       3         0

In [8]:
import numpy as np
ordinal_label = { k: i for i, k in enumerate(df['embarked'].unique(), 0)}
df['embarked'] = df['embarked'].map(ordinal_label)

In [10]:
df.sample(10)

sex  embarked  alone  pclass  survived
687    0         0   True       3         0
542    0         0  False       3         0
197    0         0  False       3         0
317    0         0   True       2         0
715    0         0   True       3         0
553    0         1   True       3         1
283    0         0   True       3         1
783    0         0  False       3         0
587    0         1  False       1         1
266    0         0  False       3         0

In [11]:
df['alone'] = np.where(df['alone'] == True, 1, 0)

In [12]:
df.head()

sex  embarked  alone  pclass  survived
0    0         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    0         0      1       3         0

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['sex', 'embarked', 'alone', 'pclass']], df['survived'], test_size=0.3, random_state=100)

In [17]:
X_train.head()

sex  embarked  alone  pclass
69     0         0      0       3
85     0         0      0       3
794    0         0      1       3
161    0         0      1       2
815    0         0      1       1

In [18]:
X_train['sex'].unique()

array([0])

In [19]:
X_train.isnull().sum()

sex         0
embarked    0
alone       0
pclass      0
dtype: int64

In [20]:
from sklearn.feature_selection import chi2
f_p_values = chi2(X_train, y_train)

In [21]:
f_p_values

(array([        nan,  7.55053653, 10.88471585, 21.97994154]),
 array([           nan, 5.99922095e-03, 9.69610546e-04, 2.75514881e-06]))

In [22]:
import pandas as pd
p_values = pd.Series(f_p_values[1])
p_values.index = X_train.columns
p_values

sex              NaN
embarked    0.005999
alone       0.000970
pclass      0.000003
dtype: float64

In [23]:
p_values.sort_index(ascending=False)

sex              NaN
pclass      0.000003
embarked    0.005999
alone       0.000970
dtype: float64